version: '3.7'
services:
    quizoo:
        build:
            context: .
        volumes:
            - static_data:/vol/web
        environment:
            - SECRET_KEY=8ahn89dub6$ak#5c(m--#m7vqzhfhvm5h+uq05t@mx*j9n(j8*
            - DEBUG=1
            - EMAIL_HOST_USER=ctrlalteliteshi2020@gmail.com
            - EMAIL_HOST_PASSWORD=passwordispassword
    proxy:
        build:
            context: ./proxy
        volumes:
            - static_data:/vol/static
        ports:
            - "8080:8080"
        depends_on: 
            - quizoo
            
volumes:
    static_data:
                



